### ISSUE TITLE
منبع اموزشی

### ISSUE THREAD

**Issue by aliraza7926** [SharifAIChallenge/AIC19-Content#1]
سلام خسته نباشید پیشنهاد میکنم این لینک رو هم به منابع اموزشیتون اضافه کنید اموزش رایگان تصویری گیت جادی هستش و به نظرم بهتر از من باشه 
https://faradars.org/courses/fvgit9609-managed-distributed-edition-using-git

**Comment by seyedparsa** [comment]
سلام
ممنونم، لطف می‌کنید در قسمت نظرات بلاگ هم لینک رو بذارید تا بقیه هم استفاده کنند؟

**Comment by aliraza7926** [comment]
(:  انجام شد
