### ISSUE TITLE
resource not found

### ISSUE THREAD

**Issue by miladmirza75** [SharifAIChallenge/AIC19-Content#2]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
\AIC19-Content-master\Scientific\Search\codes\run.py in <module>()
----> 1 from search import search
      2 from driver import *
      3 
      4 def main():
      5 

\AIC19-Content-master\Scientific\Search\codes\search.py in <module>()
----> 1 import driver
      2 from state import *
      3 
      4 def search(start_state):
      5 

\AIC19-Content-master\Scientific\Search\codes\driver.py in <module>()
      2 import argparse
      3 import timeit
----> 4 import resource
      5 from collections import deque
      6 from state import State

ModuleNotFoundError: No module named 'resource'

**Comment by seyedparsa** [comment]
کتابخانهٔ فوق را که در ویندوز پشتیبانی نمی‌شد حذف کردیم، فایل خود را به روزرسانی کنید.
